version: "3.9"
services: 
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        ports: 
            - "9200:9200"
            - "9300:9300"
        environment: 
            - discovery.type=single-node
        networks: 
            search:
                aliases: 
                    - elasticsearch
    kibana:
        depends_on: 
            - elastic
        image: docker.elastic.co/kibana/kibana:7.12.0
        ports: 
            - "5601:5601"
        networks: 
            - search
networks: 
    search: